### ISSUE TITLE
Rename to my_custom_component

### ISSUE THREAD

**Issue by rzulian** [Limych/ha-blueprint#94]
What am I missing? How do I use this blueprint to create my own component? Do I need to do a global string replace? 
Thanks
R

**Comment by Limych** [comment]
https://github.com/Limych/ha-blueprint#how

**Comment by rzulian** [comment]
Sorry, but it's not clear to me yet.
I've created my own repo with the blueprint. The devcontainer works fine. I'm able to run HA, and install the `Blueprint integration`.
My question is what I've to do to develop my own component. Copy&paste the `custom_components/integration_blueprint` dir and rename every class? Or run a cookiecutter?

**Comment by Limych** [comment]
Yes, I can see your new repository. As far as I can see, you haven't made any changes to it yet.

Now you have two options: you can leave this version of the template, or you can use my version of the template. In the second case, it will be easier for you to start from scratch: fork my template, or apply the template via the command line, as indicated in the link above.
If you fork my template, then for convenience, immediately after downloading the repository to your working computer, you need to execute the following commands from the command line:
```bash
# Add blueprint repository as remote
git remote add blueprint https://github.com/Limych/ha-blueprint.git

# Setup development environment
./bin/setup
```

The first command will include my template as a separate remote branch within your repository. You can always see new edits in this branch and can easily apply them to your project.

The second command will create a working environment for the project: connect automatic pre-commit code tests, code style correction utilities, etc.

Then you simply create your project instead of template integration `integration_blueprint`. The main code is created inside the `custom_components` directory. Unit tests - inside `tests`.

**Note!** Don't rename `integration_blueprint` inside the `custom_components` directory! Otherwise, you will constantly struggle with attempts by `git` automation to "fix" your code.

It is much more correct to create a new subdirectory by the name of your project and create new (!) files in it, by analogy with the files from `integration_blueprint`. And the `integration_blueprint` directory should be removed from your project.

**Comment by Limych** [comment]
I made a little mistake: it's better not to fork, but to generate the project according to the template: https://github.com/Limych/ha-blueprint/generate

The result is almost the same, only you will not have a bunch of old commits from the template in the history of the project.
